Implement dummy delivery provider methods for brauch
These methods are required even if they do not do anything (see specs in
the delivery module).

Avoid such errors:

  File "/odoo/src/addons/delivery/wizard/choose_delivery_carrier.py", line 44, in _onchange_order_id
    vals = self._get_shipment_rate()
  File "/odoo/src/addons/delivery/wizard/choose_delivery_carrier.py", line 69, in _get_shipment_rate
    if vals.get('success'):
AttributeError: 'NoneType' object has no attribute 'get'

For the rate, we always send 0, because anyway for cosanum the price is
overriden by the module delivery_carrier_pricelist.